### ISSUE TITLE
`keyHelper`s `additionalAllowdKinds` (sic!) feature fails with AttributeError

### ISSUE THREAD

**Issue by phorward** [viur-framework/viur-datastore#11]
The utils.keyHelper features a parameter `additionalAllowdKinds` (sic!), which doesn't work when a str containing a valid key is provided.

This is the result when trying to use it:
```
Traceback (most recent call last):
  File "/home/neo/.local/share/virtualenvs/event-viur-woNjR8mT/lib/python3.9/site-packages/viur/core/request.py", line 249, in processRequest
    self.findAndCall(path)
  File "/home/neo/.local/share/virtualenvs/event-viur-woNjR8mT/lib/python3.9/site-packages/viur/core/request.py", line 567, in findAndCall
    res = caller(*newArgs, **newKwargs)
  File "/home/neo/.local/share/virtualenvs/event-viur-woNjR8mT/lib/python3.9/site-packages/viur/core/prototypes/list.py", line 218, in edit
    or not skel.fromClient(kwargs)  # failure on reading into the bones
  File "/home/neo/.local/share/virtualenvs/event-viur-woNjR8mT/lib/python3.9/site-packages/viur/core/skeleton.py", line 647, in fromClient
    complete = super().fromClient(skelValues, data)
  File "/home/neo/.local/share/virtualenvs/event-viur-woNjR8mT/lib/python3.9/site-packages/viur/core/skeleton.py", line 327, in fromClient
    errors = _bone.fromClient(skelValues, key, data)
  File "/home/neo/.local/share/virtualenvs/event-viur-woNjR8mT/lib/python3.9/site-packages/viur/core/bones/base.py", line 381, in fromClient
    res, parseErrors = self.singleValueFromClient(parsedData, skel, name, data)
  File "/home/neo/.local/share/virtualenvs/event-viur-woNjR8mT/lib/python3.9/site-packages/viur/core/bones/key.py", line 30, in singleValueFromClient
    key = db.keyHelper(value, self.allowed_kinds[0], self.allowed_kinds[1:])
  File "/home/neo/.local/share/virtualenvs/event-viur-woNjR8mT/lib/python3.9/site-packages/viur/datastore/utils.py", line 63, in keyHelper
    if decodedKey.kind != targetKind and (not additionalAllowdKinds or inKey.kind not in additionalAllowdKinds):
AttributeError: 'str' object has no attribute 'kind'
```

1. PLEASE rename `additionalAllowdKinds` into `additionalAllowedKinds`, or best `additional_allowed_kinds`
2. The condition should be `if decodedKey.kind != targetKind and (not additionalAllowdKinds or decodedKey.kind not in additionalAllowdKinds):`

**Comment by skoegl** [comment]
That issue was been fixed via #13
